In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv(
    "Exam_Score_Prediction.csv",
    converters={'sleep_quality': lambda x: 0 if x == 'poor' else x}
)

In [39]:
data.head(5)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,0,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,0,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,0,coaching,low,moderate,43.7

In [4]:
data.tail(5)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [5]:
data.sample(5)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
11987,11988,24,female,diploma,4.39,41.4,yes,6.5,good,group study,high,easy,76.1
6171,6172,19,other,b.com,6.24,41.2,yes,4.9,average,online videos,medium,easy,74.1
1681,1682,17,other,ba,1.72,42.2,yes,5.7,good,mixed,medium,moderate,58.1
103,104,17,male,bba,7.00,80.6,yes,9.6,poor,group study,medium,moderate,88.5
18980,18981,21,other,b.sc,0.91,84.8,no,5.2,poor,online videos,low,easy,38.9

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  str
 3   course            20000 non-null  str
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  str
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  str
 9   study_method      20000 non-null  str
 10  facility_rating   20000 non-null  str
 11  exam_difficulty   20000 non-null  str
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), str(7)
memory usage: 2.7 MB

In [7]:
data.describe()

,student_id,age,study_hours,class_attendance,sleep_hours,exam_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,10000.504600,20.473300,4.007604,70.017365,7.00856,62.513225
std,5773.654959,2.284458,2.308313,17.282262,1.73209,18.908491
min,1.000000,17.000000,0.080000,40.600000,4.10000,19.599000
25%,5000.750000,18.000000,2.000000,55.100000,5.50000,48.800000
50%,10000.500000,20.000000,4.040000,69.900000,7.00000,62.600000
75%,15000.250000,22.000000,6.000000,85.000000,8.50000,76.300000
max,20001.000000,24.000000,7.910000,99.400000,9.90000,100.000000

In [8]:
data.shape

(20000, 13)

In [9]:
chunksdata=pd.read_csv('Exam_Score_Prediction.csv',chunksize=5000)

In [10]:
for i in chunksdata:
    print(i.shape)

(5000, 13)
(5000, 13)
(5000, 13)
(5000, 13)

In [11]:
newdata=data.iloc[:5000,8:]

In [12]:
newdata.head()

  sleep_quality   study_method facility_rating exam_difficulty  exam_score
0          poor       coaching             low            hard        58.9
1       average  online videos          medium        moderate        54.8
2          poor       coaching            high        moderate        90.3
3       average  online videos             low        moderate        29.7
4          poor       coaching             low        moderate        43.7

In [13]:
newdata.shape

(5000, 5)

In [26]:
n_New_data=pd.read_csv("Exam_Score_Prediction.csv",usecols=['student_id','age','class_attendance','exam_score'],nrows=5000) #dtype={'class_attendance':'int64','exam_score':'int64'}

In [29]:
n_New_data['class_attendance'] = n_New_data['class_attendance'].astype('int64')


n_New_data['exam_score'] = n_New_data['exam_score'].astype('int64')

In [19]:
n_New_data.head()

   student_id  age  class_attendance  exam_score
0           1   17              92.9        58.9
1           2   23              64.8        54.8
2           3   22              76.8        90.3
3           4   20              48.4        29.7
4           5   20              71.6        43.7

In [21]:
n_New_data.shape

(5000, 4)

In [30]:
n_New_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        5000 non-null   int64
 1   age               5000 non-null   int64
 2   class_attendance  5000 non-null   int64
 3   exam_score        5000 non-null   int64
dtypes: int64(4)
memory usage: 156.4 KB